name: Test Windows Installation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test-windows-install:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Visual C++ Build Tools
        uses: microsoft/setup-msbuild@v2

      - name: Install in development mode
        shell: pwsh
        run: |
          # Install in development mode with all dependencies
          python -m pip install -e .[dev]

      - name: Test basic functionality
        shell: pwsh
        run: |
          # Initialize configuration
          python -m rag_retriever --init

          # Create test content
          $testDir = "test-docs"
          mkdir $testDir
          Set-Content -Path "$testDir\test.txt" -Value "Test content for indexing"

          # Try ingesting the text file
          python -m rag_retriever --ingest-file "$testDir\test.txt"

          # Try a basic search query
          python -m rag_retriever --query "test content"
