name: Test Windows Installation

on:
  # Manual trigger only
  workflow_dispatch:

jobs:
  test-windows-install:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    # Add global timeout
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Visual C++ Build Tools
        uses: microsoft/setup-msbuild@v2

      - name: Install in development mode
        shell: pwsh
        run: |
          # Install in development mode with all dependencies
          python -m pip install -e .[dev]

          # Print installed version and location
          python -c "import rag_retriever; print(f'Version: {rag_retriever.__version__}'); print(f'Location: {rag_retriever.__file__}')"

      - name: Test basic functionality
        shell: pwsh
        run: |
          # Enable verbose output
          $env:RAG_RETRIEVER_DEBUG = "1"

          Write-Host "Starting initialization..."
          # Initialize with default config (non-interactive)
          python -m rag_retriever --init --non-interactive

          Write-Host "Creating test content..."
          $testDir = "test-docs"
          mkdir $testDir
          Set-Content -Path "$testDir\test.txt" -Value "Test content for indexing"

          Write-Host "Testing file ingestion..."
          python -m rag_retriever --ingest-file "$testDir\test.txt" --verbose

          Write-Host "Testing search..."
          python -m rag_retriever --query "test content" --verbose
